---

- name: machine_cible
  hosts: wordpress
  become: yes
  tasks:
    - name: ping_machine_cible
      ping:

#PHP
    - name: Add the ondrej PHP PPA
      apt_repository:
        repo: 'ppa:ondrej/php'


    - name: Install PHP
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-fpm
        - php-mysql
        - php-xml


    - name: Remove apache2
      package:
        name: apache2
        state: absent

# MySQL
    - name: Install MySQL
      package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python-mysqldb


    - name: Generate new root password
      command: openssl rand -hex 7
      args:
        creates: /root/.my.cnf
      register: mysql_new_root_pass


    - name: Remove anonymous users
      mysql_user:
        name: ""
        state: absent


    - name: Remove test database
      mysql_db:
        name: test
        state: absent

    - name: Output new root password
      debug:
        msg: "New root password is {{ mysql_new_root_pass.stdout }}"

    - name: Update root password
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_new_root_pass.stdout }}"
      loop:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost


    - name: Create my.cnf
      template:
        src: templates/mysql/my.cnf.j2
        dest: /root/.my.cnf
