---

- name: machine_cible
  hosts: wordpress
  become: yes
  tasks:
    - name: ping_machine_cible
      ping:

  #PHP
  - name: Add the ondrej PHP PPA
    apt_repository:
      repo: 'ppa:ondrej/php'


  - name: Install PHP
    package:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-fpm
      - php-mysql
      - php-xml

  - name: Remove apache2
    package:
      name: apache2
      state: absent
